name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: docker build -f src/main/docker/Dockerfile.native -t jjbeto/echo:${{ github.sha }} .
    - name: Publish to DockerHub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push jjbeto/echo:${{ github.sha }}
